name: rebuildAndroidAll
on:
  workflow_dispatch:
jobs:
  configure:
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: recursive
      
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Haxelibs
        run: |
          haxelib setup haxelib
          sudo chmod -R 777 haxelib
          haxelib --quiet install lime 7.9.0
          haxelib --quiet install openfl 9.1.0
          haxelib --quiet --never run lime setup
          haxelib git extension-ffmpeg https://github.com/Sirox228/extension-ffmpeg
          
      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set lime 7.9.0
          haxelib set openfl 9.1.0
          haxelib list
          sudo chmod -R 777 *
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          
  compile-ffmpeg:
    needs: configure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, arm32, x86, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Compile arm64
        if: matrix.arch == 'arm64'
        run: |
          cd haxelib/extension-ffmpeg/git/lib.src
          sudo chmod -R 777 *
          ./build_android64.sh
        env:
          ANDROID_NDK_HOME: ${{ configure.steps.setup-ndk.outputs.ndk-path }}

      - name: Compile arm32
        if: matrix.arch == 'arm32'
        run: |
          cd haxelib/extension-ffmpeg/git/lib.src
          sudo chmod -R 777 *
          ./build_android32.sh
        env:
          ANDROID_NDK_HOME: ${{ configure.steps.setup-ndk.outputs.ndk-path }}

      - name: Compile x86
        if: matrix.arch == 'x86'
        run: |
          cd haxelib/extension-ffmpeg/git/lib.src
          sudo chmod -R 777 *
          ./build_androidx86.sh
        env:
          ANDROID_NDK_HOME: ${{ configure.steps.setup-ndk.outputs.ndk-path }}

      - name: Compile x86_64
        if: matrix.arch == 'x86_64'
        run: |
          cd haxelib/extension-ffmpeg/git/lib.src
          sudo chmod -R 777 *
          ./build_androidx86_64.sh
        env:
          ANDROID_NDK_HOME: ${{ configure.steps.setup-ndk.outputs.ndk-path }}
          
  lime-rebuild-ffmpeg:
    needs: compile-ffmpeg
    runs-on: ubuntu-latest
    steps:
      - name: Lime Rebuild
        run: haxelib run lime rebuild extension-ffmpeg android

      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Android Libs
          path: ndll/Android