name: rebuildAndroidAll
on:
  workflow_dispatch:
jobs:
  compile-ffmpeg:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, arm32, x86, x86_64]
    steps:
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: install
        run: |
          haxelib setup haxelib
          sudo chmod -R 777 haxelib
          haxelib git extension-ffmpeg https://github.com/Sirox228/extension-ffmpeg

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Compile arm64
        if: matrix.arch == 'arm64'
        run: |
          cd haxelib/extension-ffmpeg/git/lib.src
          sudo chmod -R 777 *
          ./build_android64.sh
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile arm32
        if: matrix.arch == 'arm32'
        run: |
          cd haxelib/extension-ffmpeg/git/lib.src
          sudo chmod -R 777 *
          ./build_android32.sh
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile x86
        if: matrix.arch == 'x86'
        run: |
          cd haxelib/extension-ffmpeg/git/lib.src
          sudo chmod -R 777 *
          ./build_androidx86.sh
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile x86_64
        if: matrix.arch == 'x86_64'
        run: |
          cd haxelib/extension-ffmpeg/git/lib.src
          sudo chmod -R 777 *
          ./build_androidx86_64.sh
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: remove git useless things
        run: |
          rm -r haxelib/extension-ffmpeg/git/lib.src/ffmpeg/.git
          rm -r haxelib/extension-ffmpeg/git/.git

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: tmp${{matrix.arch}}
          path: haxelib
          
  lime-rebuild-ffmpeg:
    needs: compile-ffmpeg
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: install
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          haxelib setup haxelib
          sudo chmod -R 777 haxelib
          sudo apt install libgl1-mesa-dev libglu1-mesa-dev g++ g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev libpulse-dev -y
          git clone --single-branch --branch submodules --recurse-submodules https://github.com/player-03/lime.git ../lime
          haxelib dev lime ../lime
          haxelib --quiet install format
          haxelib --quiet install hxp
          haxelib --quiet install hxcpp
          haxelib run lime rebuild tools
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib run lime rebuild android
          haxelib --quiet --never run lime setup
          haxelib --quiet install openfl 9.1.0
          haxelib set openfl 9.1.0
          haxelib list
          sudo chmod -R 777 *

      - name: Download arm64 Builded ffmpeg
        uses: actions/download-artifact@v1
        with:
          name: tmparm64
          path: haxelib

      - name: Download arm32 Builded ffmpeg
        uses: actions/download-artifact@v1
        with:
          name: tmparm32
          path: haxelib

      - name: Download x86 Builded ffmpeg
        uses: actions/download-artifact@v1
        with:
          name: tmpx86
          path: haxelib

      - name: Download x86_64 Builded ffmpeg
        uses: actions/download-artifact@v1
        with:
          name: tmpx86_64
          path: haxelib
      
      - name: remove tmp arm64
        uses: geekyeggo/delete-artifact@v1
        with:
          name: tmparm64

      - name: remove tmp arm32
        uses: geekyeggo/delete-artifact@v1
        with:
          name: tmparm32

      - name: remove tmp x86
        uses: geekyeggo/delete-artifact@v1
        with:
          name: tmpx86

      - name: remove tmp x86_64
        uses: geekyeggo/delete-artifact@v1
        with:
          name: tmpx86_64
        
      - name: Lime Rebuild
        run: haxelib run lime rebuild extension-ffmpeg android -fno-integrated-as

      - name: upload rebuilded libs
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Android Libs
          path: haxelib/extension-ffmpeg/git/ndll/Android
