# This is a basic workflow to help you get started with Actions

name: rebuildAndroid64

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  rebuildAndroid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Haxelibs
        run: |
          haxelib setup haxelib
          sudo chmod -R 777 haxelib
          haxelib --quiet install lime 7.9.0
          haxelib --quiet install openfl 9.1.0
          haxelib --quiet --never run lime setup
          haxelib git extension-ffmpeg https://github.com/Sirox228/extension-ffmpeg
          

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set lime 7.9.0
          haxelib set openfl 9.1.0
          haxelib list
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: |
          sudo chmod -R 777 *
          cd haxelib/extension-ffmpeg/git/lib.src
          sudo chmod -R 777 *
          ./build_android64.sh
          cd ../
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Rebuild64
        run: haxelib run lime rebuild extension-ffmpeg android -D HXCPP_ARM64

      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: androidBuild
          path: lib.build
