name: test
on:
  workflow_dispatch:
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Lime Test
        run: |
          haxelib git lime https://github.com/player-03/lime.git submodules
          haxelib path lime

  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Lime Test
        run: |
          sudo apt install git -y # just to be sure that git is installed
          haxelib git lime https://github.com/player-03/lime.git submodules
          pushd /opt/hostedtoolcache/haxe/4.2.5/x64/lib/lime/git
          git branch # "submodules" should be highlighted
          ls project/lib/cairo-files.xml # should print the file
          ls project/lib/cairo/files.xml # should say "no such file or directory"
          grep -n "#include <pixman.h>" project/lib/cairo/src/cairoint.h # should print line 69, not 71
          popd # optional cleanup

  test3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Lime Test
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          sudo apt install libgl1-mesa-dev libglu1-mesa-dev g++ g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev libpulse-dev -y
          git clone --single-branch --branch submodules --recurse-submodules https://github.com/player-03/lime.git ../lime
          haxelib dev lime ../lime
          haxelib --quiet install format
          haxelib --quiet install hxp
          haxelib --quiet install hxcpp
          haxelib run lime rebuild tools
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib run lime rebuild android
